// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV_00KJvGR2vSYQIxVtq1T6oOcv_kTU80',
    appId: '1:1047947981004:web:69d3103a784406ab989269',
    messagingSenderId: '1047947981004',
    projectId: 'mw-antenatalcare',
    authDomain: 'mw-antenatalcare.firebaseapp.com',
    storageBucket: 'mw-antenatalcare.firebasestorage.app',
    measurementId: 'G-YZ7EPMX7LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQYck-0bY6cwgvG2Bz0AedQkp57v9CrjU',
    appId: '1:1047947981004:android:f2d36a479c907d9d989269',
    messagingSenderId: '1047947981004',
    projectId: 'mw-antenatalcare',
    storageBucket: 'mw-antenatalcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCOyDSGxP9VfjMsYFcONvE_noF9ThytnI',
    appId: '1:1047947981004:ios:979dd2cffc0ce5f2989269',
    messagingSenderId: '1047947981004',
    projectId: 'mw-antenatalcare',
    storageBucket: 'mw-antenatalcare.firebasestorage.app',
    iosBundleId: 'com.example.mwAntenatalcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCOyDSGxP9VfjMsYFcONvE_noF9ThytnI',
    appId: '1:1047947981004:ios:979dd2cffc0ce5f2989269',
    messagingSenderId: '1047947981004',
    projectId: 'mw-antenatalcare',
    storageBucket: 'mw-antenatalcare.firebasestorage.app',
    iosBundleId: 'com.example.mwAntenatalcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV_00KJvGR2vSYQIxVtq1T6oOcv_kTU80',
    appId: '1:1047947981004:web:257fb0fc6392834d989269',
    messagingSenderId: '1047947981004',
    projectId: 'mw-antenatalcare',
    authDomain: 'mw-antenatalcare.firebaseapp.com',
    storageBucket: 'mw-antenatalcare.firebasestorage.app',
    measurementId: 'G-33W3VWZEXE',
  );
}
